services:
  geant4:
    build: .
    container_name: geant4_desktop
    ports:
   -"IN_PORT":"OUT_PORT"
    environment:
      # Пароль для доступа через noVNC (можно изменить)
      - VNC_PASSWORD=${VNC_PASSWORD:-"PASSWORD"}
    volumes:
      # Монтирование локальной папки workspace внутрь контейнера
      - ./workspace:/workspace
    # Выделение общей памяти для корректной работы Qt/OpenGL (предотвращает артефакты)
    shm_size: '2gb'
    restart: unless-stopped
